# Please consult conda-forge/core before doing this
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.11"                # [osx and x86_64]
c_stdlib_version:   # [unix]
  - "2.17"          # [linux]
