{% set name = "StringZilla" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ashvardanian/StringZilla/archive/v{{ version }}.tar.gz
  sha256: fc3203dbae35c299e7056b175ad84a7aff992218b9e7a9a7ba2b9c94d2ee59e0
  #patches:
    #- patches/0001-fix-build-option.patch

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pip
  run:
    - python

test:
  imports:
    - stringzilla
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ashvardanian/StringZilla
  summary: SIMD-accelerated string search, sort, hashes, fingerprints, & edit distances
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mukhery
    - rxm7706
    - pb01ka
