{% set name = "StringZilla" %}
{% set version = "3.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ashvardanian/StringZilla/archive/v{{ version }}.tar.gz
  sha256: 94f10a6ee4f9231afe3dd314cb1cbe5901e9098c44ba538362c529d79ff01ce5
  patches:
    - patches/0001-fix-build-option.patch

build:
  entry_points:
    - sz_split=cli.split:main
    - sz_wc=cli.wc:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pip
  run:
    - python

test:
  imports:
    - cli
  commands:
    - pip check
    - sz_split --help
    - sz_wc --help
  requires:
    - pip

about:
  home: https://github.com/ashvardanian/StringZilla
  summary: SIMD-accelerated string search, sort, hashes, fingerprints, & edit distances
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mukhery
    - rxm7706
