{% set name = "StringZilla" %}
{% set version = "3.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ashvardanian/StringZilla/archive/v{{ version }}.tar.gz
  sha256: 4913a07ba9181dc9f138b231d37e37e6150c7ccd05c9399d46e0155a2c51cd6a

build:
  entry_points:
    - sz_split=cli.split:main
    - sz_wc=cli.wc:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=42
    - wheel
    - pip
  run:
    - python

test:
  imports:
    - cli
  commands:
    - pip check
    - sz_split --help
    - sz_wc --help
  requires:
    - pip

about:
  home: https://github.com/ashvardanian/StringZilla
  summary: SIMD-accelerated string search, sort, hashes, fingerprints, & edit distances
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
